package simulator.entity.application;

import java.util.HashMap;

import desmoj.core.simulator.Entity;
import desmoj.core.simulator.Model;

import simulator.entity.topology.NFSTopologyController;

public abstract class NFSTrafficGenerator extends Entity {

	protected NFSTopologyController topocontroller = null;
	
	protected HashMap<String, String> oneToOneTrafficMap = null;//src ip -> dst ip
	protected HashMap<String, String[]> oneToManyTrafficMap = null;
	
	public NFSTrafficGenerator(Model model, String entityName, boolean showInReport,
			NFSTopologyController tpctrl) {
		super(model, entityName, showInReport);
		topocontroller = tpctrl;
		init();
	}
	
	protected void init() {
		oneToOneTrafficMap = new HashMap<String, String>();
		oneToManyTrafficMap = new HashMap<String, String[]>();
	}
	
	/**
	 * get the destination host of the flow generated by the machine with srcip
	 * @param srcip, ip address of the source host
	 * @return, destination ip address
	 */
	public String getOneToOneTarget(String srcip) {
		return oneToOneTrafficMap.get(srcip);
	}
	
	public abstract String [] getOneToManyTarget(int targetsnum);
	public abstract void run();
}
